#!/usr/bin/env python3
"""
FIREKit ecosystem runner.

Runs every product's demo pipeline, validates the emitted hub JSON, and
bundles everything into hub/data/products.js for the dashboard
(open hub/index.html in a browser, or `python3 -m http.server -d hub`).

Usage:
    python3 run_all.py              # run all product demos + bundle
    python3 run_all.py --bundle-only  # just rebuild products.js from existing JSON
    python3 run_all.py --only signalml,riskguard
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent
HUB_DATA = ROOT / "hub" / "data"

# product directory -> python package (demo module is <package>.demo)
PRODUCTS: dict[str, str] = {
    "vectorforge": "vectorforge",
    "datastream": "datastream",
    "alphalab": "alphalab",
    "signalml": "signalml",
    "sentimentpulse": "sentimentpulse",
    "deeptrader": "deeptrader",
    "executioncore": "executioncore",
    "riskguard": "riskguard",
    "portfolioengine": "portfolioengine",
}

REQUIRED_KEYS = {
    "schema_version", "product", "title", "tagline", "version",
    "generated_at", "status", "summary_metrics", "charts", "tables",
}


def run_demo(product_dir: str, package: str) -> tuple[bool, str]:
    """Run one product demo; return (ok, message)."""
    cwd = ROOT / product_dir
    if not cwd.is_dir():
        return False, "directory missing"
    start = time.perf_counter()
    proc = subprocess.run(
        [sys.executable, "-m", f"{package}.demo"],
        cwd=cwd,
        capture_output=True,
        text=True,
        timeout=300,
    )
    elapsed = time.perf_counter() - start
    if proc.returncode != 0:
        tail = (proc.stderr or proc.stdout).strip().splitlines()[-8:]
        return False, f"exit {proc.returncode} in {elapsed:.1f}s\n    " + "\n    ".join(tail)
    return True, f"ok in {elapsed:.1f}s"


def validate(path: Path) -> list[str]:
    """Return a list of schema problems (empty == valid)."""
    problems: list[str] = []
    try:
        payload = json.loads(path.read_text())
    except (json.JSONDecodeError, OSError) as exc:
        return [f"unreadable JSON: {exc}"]
    missing = REQUIRED_KEYS - payload.keys()
    if missing:
        problems.append(f"missing keys: {sorted(missing)}")
    if payload.get("product") != path.stem:
        problems.append(f"product field {payload.get('product')!r} != filename {path.stem!r}")
    if not payload.get("summary_metrics"):
        problems.append("summary_metrics is empty")
    for chart in payload.get("charts", []):
        n_x = len(chart.get("x", []))
        if n_x > 500:
            problems.append(f"chart {chart.get('id')}: {n_x} x-points > 500")
        for series in chart.get("series", []):
            if len(series.get("data", [])) != n_x:
                problems.append(
                    f"chart {chart.get('id')}: series {series.get('name')!r} "
                    f"length {len(series.get('data', []))} != x length {n_x}"
                )
    if "NaN" in path.read_text():
        problems.append("contains NaN literal (not valid JSON)")
    return problems


def bundle() -> int:
    """Bundle hub/data/*.json into hub/data/products.js. Returns product count."""
    entries = []
    for path in sorted(HUB_DATA.glob("*.json")):
        entries.append(json.loads(path.read_text()))
    out = HUB_DATA / "products.js"
    generated = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    out.write_text(
        f"// Generated by run_all.py at {generated} — do not edit by hand.\n"
        f"window.FIREKIT_DATA = {json.dumps(entries, indent=2)};\n"
    )
    return len(entries)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--bundle-only", action="store_true", help="skip demos, just rebundle")
    parser.add_argument("--only", default="", help="comma-separated subset of products to run")
    args = parser.parse_args()

    HUB_DATA.mkdir(parents=True, exist_ok=True)
    failures: list[str] = []

    if not args.bundle_only:
        subset = {s.strip() for s in args.only.split(",") if s.strip()}
        targets = {k: v for k, v in PRODUCTS.items() if not subset or k in subset}
        print(f"Running {len(targets)} product demos...\n")
        for product_dir, package in targets.items():
            ok, msg = run_demo(product_dir, package)
            print(f"  {'PASS' if ok else 'FAIL'}  {product_dir:<16} {msg}")
            if not ok:
                failures.append(product_dir)

    print("\nValidating hub JSON...")
    for path in sorted(HUB_DATA.glob("*.json")):
        problems = validate(path)
        status = "ok" if not problems else "; ".join(problems)
        print(f"  {path.stem:<16} {status}")
        if problems:
            failures.append(path.stem)

    count = bundle()
    print(f"\nBundled {count} products into hub/data/products.js")
    print("Open hub/index.html in a browser (or: python3 -m http.server -d hub 8080)")

    if failures:
        print(f"\nFAILURES: {sorted(set(failures))}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
