/* FIREKit Hub dashboard renderer.
 * Renders window.FIREKIT_DATA (generated by run_all.py into data/products.js)
 * as product sections with metric cards, SVG charts, and tables.
 * No external dependencies: works from file:// or any static server.
 */
(function () {
  "use strict";

  const PALETTE = ["#5b9cf6", "#ff7a45", "#3fb97f", "#c879e8", "#ffd166"];
  // Stack order mirrors the ecosystem architecture, bottom (infra) to top.
  const PRODUCT_ORDER = [
    "vectorforge", "datastream", "alphalab", "signalml", "sentimentpulse",
    "deeptrader", "portfolioengine", "riskguard", "executioncore",
  ];

  const data = Array.isArray(window.FIREKIT_DATA) ? window.FIREKIT_DATA.slice() : [];
  const dashboard = document.getElementById("dashboard");
  const emptyState = document.getElementById("empty-state");
  const nav = document.getElementById("product-nav");
  const meta = document.getElementById("hub-meta");

  if (!data.length) return; // keep empty-state visible
  emptyState.remove();

  data.sort((a, b) => {
    const ia = PRODUCT_ORDER.indexOf(a.product);
    const ib = PRODUCT_ORDER.indexOf(b.product);
    return (ia === -1 ? 99 : ia) - (ib === -1 ? 99 : ib);
  });

  const newest = data.map((d) => d.generated_at).sort().pop();
  meta.textContent = `${data.length} products · generated ${newest || "?"}`;

  for (const product of data) {
    nav.appendChild(el("a", { href: `#${product.product}` }, product.title));
    dashboard.appendChild(renderProduct(product));
  }

  /* ---------- rendering ---------- */

  function renderProduct(p) {
    const section = el("section", {
      class: `product-section${p.status === "error" ? " status-error" : ""}`,
      id: p.product,
    });

    const header = el("div", { class: "product-header" });
    header.appendChild(el("h2", {}, p.title));
    header.appendChild(el("span", { class: "version" }, `${p.product} v${p.version || "?"}`));
    section.appendChild(header);
    section.appendChild(el("p", { class: "tagline" }, p.tagline || ""));

    if (Array.isArray(p.summary_metrics) && p.summary_metrics.length) {
      const row = el("div", { class: "metrics-row" });
      for (const m of p.summary_metrics) row.appendChild(metricCard(m));
      section.appendChild(row);
    }

    if (Array.isArray(p.charts) && p.charts.length) {
      const grid = el("div", { class: "charts-grid" });
      for (const c of p.charts) grid.appendChild(chartBox(c));
      section.appendChild(grid);
    }

    if (Array.isArray(p.tables) && p.tables.length) {
      const grid = el("div", { class: "tables-grid" });
      for (const t of p.tables) grid.appendChild(tableBox(t));
      section.appendChild(grid);
    }

    if (p.notes) section.appendChild(el("p", { class: "notes" }, p.notes));
    return section;
  }

  function metricCard(m) {
    const card = el("div", { class: "metric-card" });
    card.appendChild(el("div", { class: "label" }, m.label));
    const text = `${m.value}${m.unit ? " " + m.unit : ""}`;
    let cls = "value";
    const num = parseFloat(String(m.value).replace(/[%,$]/g, ""));
    if (/^-/.test(String(m.value))) cls += " neg";
    else if (!Number.isNaN(num) && /[%]/.test(String(m.value)) && num > 0) cls += " pos";
    card.appendChild(el("div", { class: cls }, text));
    return card;
  }

  function tableBox(t) {
    const box = el("div", { class: "table-box" });
    box.appendChild(el("h3", {}, t.title));
    const table = el("table", {});
    const thead = el("thead", {});
    const headRow = el("tr", {});
    for (const c of t.columns) headRow.appendChild(el("th", {}, String(c)));
    thead.appendChild(headRow);
    table.appendChild(thead);
    const tbody = el("tbody", {});
    for (const row of t.rows) {
      const tr = el("tr", {});
      for (const cell of row) tr.appendChild(el("td", {}, cell === null ? "—" : String(cell)));
      tbody.appendChild(tr);
    }
    table.appendChild(tbody);
    box.appendChild(table);
    return box;
  }

  /* ---------- SVG charts ---------- */

  const W = 460, H = 240;
  const M = { top: 12, right: 12, bottom: 34, left: 52 };
  const IW = W - M.left - M.right;
  const IH = H - M.top - M.bottom;

  function chartBox(c) {
    const box = el("div", { class: "chart-box" });
    box.appendChild(el("h3", {}, c.title));
    let svg;
    if (c.type === "bar") svg = barChart(c);
    else svg = lineChart(c); // line + scatter share scaffolding
    box.appendChild(svg);

    if ((c.series || []).length > 1) {
      const legend = el("div", { class: "legend" });
      c.series.forEach((s, i) => {
        const item = el("span", {});
        item.appendChild(el("i", { style: `background:${PALETTE[i % PALETTE.length]}` }));
        item.appendChild(document.createTextNode(s.name));
        legend.appendChild(item);
      });
      box.appendChild(legend);
    }
    return box;
  }

  function extent(series) {
    let lo = Infinity, hi = -Infinity;
    for (const s of series) {
      for (const v of s.data) {
        if (v === null || Number.isNaN(v)) continue;
        if (v < lo) lo = v;
        if (v > hi) hi = v;
      }
    }
    if (lo === Infinity) { lo = 0; hi = 1; }
    if (lo === hi) { lo -= 1; hi += 1; }
    const pad = (hi - lo) * 0.06;
    return [lo - pad, hi + pad];
  }

  function niceTicks(lo, hi, n) {
    const span = hi - lo;
    const step = Math.pow(10, Math.floor(Math.log10(span / n)));
    const candidates = [step, step * 2, step * 2.5, step * 5, step * 10];
    const chosen = candidates.find((s) => span / s <= n) || step * 10;
    const ticks = [];
    for (let v = Math.ceil(lo / chosen) * chosen; v <= hi; v += chosen) ticks.push(v);
    return ticks;
  }

  function fmt(v) {
    const abs = Math.abs(v);
    if (abs >= 1e6) return (v / 1e6).toFixed(1) + "M";
    if (abs >= 1e4) return (v / 1e3).toFixed(0) + "k";
    if (abs >= 100) return v.toFixed(0);
    if (abs >= 1) return v.toFixed(1);
    return v.toFixed(2);
  }

  function svgRoot(c) {
    const svg = svgEl("svg", { viewBox: `0 0 ${W} ${H}` });
    const [lo, hi] = extent(c.series);
    const y = (v) => M.top + IH - ((v - lo) / (hi - lo)) * IH;
    for (const t of niceTicks(lo, hi, 5)) {
      svg.appendChild(svgEl("line", {
        class: "grid-line", x1: M.left, x2: W - M.right, y1: y(t), y2: y(t),
      }));
      svg.appendChild(svgEl("text", {
        class: "tick-label", x: M.left - 6, y: y(t) + 3, "text-anchor": "end",
      }, fmt(t)));
    }
    if (c.y_label) {
      svg.appendChild(svgEl("text", {
        class: "axis-label", x: 12, y: M.top + IH / 2,
        transform: `rotate(-90 12 ${M.top + IH / 2})`, "text-anchor": "middle",
      }, c.y_label));
    }
    return { svg, y, lo, hi };
  }

  function xTickLabels(svg, labels, xPos) {
    const n = labels.length;
    if (!n) return;
    const every = Math.max(1, Math.ceil(n / 6));
    for (let i = 0; i < n; i += every) {
      svg.appendChild(svgEl("text", {
        class: "tick-label", x: xPos(i), y: H - M.bottom + 14, "text-anchor": "middle",
      }, truncate(String(labels[i]), 11)));
    }
  }

  function lineChart(c) {
    const { svg, y } = svgRoot(c);
    const n = Math.max(...c.series.map((s) => s.data.length), c.x.length);
    const x = (i) => M.left + (n <= 1 ? IW / 2 : (i / (n - 1)) * IW);
    c.series.forEach((s, si) => {
      const color = PALETTE[si % PALETTE.length];
      if (c.type === "scatter") {
        s.data.forEach((v, i) => {
          if (v === null) return;
          svg.appendChild(svgEl("circle", { cx: x(i), cy: y(v), r: 2.4, fill: color }));
        });
        return;
      }
      let d = "", pen = false;
      s.data.forEach((v, i) => {
        if (v === null) { pen = false; return; }
        d += `${pen ? "L" : "M"}${x(i).toFixed(1)},${y(v).toFixed(1)}`;
        pen = true;
      });
      svg.appendChild(svgEl("path", {
        d, fill: "none", stroke: color, "stroke-width": 1.7,
        "stroke-linejoin": "round", "stroke-linecap": "round",
      }));
    });
    xTickLabels(svg, c.x, x);
    return svg;
  }

  function barChart(c) {
    const { svg, y } = svgRoot(c);
    const n = Math.max(...c.series.map((s) => s.data.length), c.x.length);
    const groupW = IW / Math.max(n, 1);
    const nSeries = c.series.length;
    const barW = Math.min(34, (groupW * 0.72) / nSeries);
    const zero = y(Math.max(0, extentLo(c)));
    c.series.forEach((s, si) => {
      const color = PALETTE[si % PALETTE.length];
      s.data.forEach((v, i) => {
        if (v === null) return;
        const cx = M.left + groupW * i + groupW / 2;
        const bx = cx - (barW * nSeries) / 2 + si * barW;
        const top = Math.min(y(v), zero);
        const h = Math.max(1, Math.abs(y(v) - zero));
        svg.appendChild(svgEl("rect", {
          x: bx, y: top, width: barW - 2, height: h, fill: color, rx: 2,
        }));
      });
    });
    xTickLabels(svg, c.x, (i) => M.left + groupW * i + groupW / 2);
    return svg;

    function extentLo(chart) {
      const [lo] = extent(chart.series);
      return lo;
    }
  }

  /* ---------- DOM helpers ---------- */

  function el(tag, attrs, text) {
    const node = document.createElement(tag);
    for (const [k, v] of Object.entries(attrs || {})) node.setAttribute(k, v);
    if (text !== undefined) node.textContent = text;
    return node;
  }

  function svgEl(tag, attrs, text) {
    const node = document.createElementNS("http://www.w3.org/2000/svg", tag);
    for (const [k, v] of Object.entries(attrs || {})) node.setAttribute(k, v);
    if (text !== undefined) node.textContent = text;
    return node;
  }

  function truncate(s, len) {
    return s.length > len ? s.slice(0, len - 1) + "…" : s;
  }
})();
